### ISSUE TITLE
Portworx Pod Fails Looking for Mounted Directories that Don't Exist

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [portworx/helm#160]
**BUG REPORT**

**What happened**:
After deployment, the main portworx pod keeps crashing with these errors below. It is looking for mounted volumes that I don't think it should be looking for. Why does it use the oci-monitor Docker image when I chose no monitoring and no OCI?

```
time="2020-08-18T19:53:22Z" level=info msg="Input arguments: /px-oci-mon -s /dev/sdc -k etcd:http://server1:2379,http://server2:2379 -c ebdc-poc -secret_type k8s -ca /etc/pwx/etcdcerts/ca.pem -cert /etc/pwx/etcdcerts/client.pem -key /etc/pwx/etcdcerts/client-key.pem -x kubernetes"
time="2020-08-18T19:53:22Z" level=info msg="Updated arguments: /px-oci-mon -s /dev/sdc -k etcd:http://server1:2379,http://server2:2379 -c ebdc-poc -secret_type k8s -ca /etc/pwx/etcdcerts/ca.pem -cert /etc/pwx/etcdcerts/client.pem -key /etc/pwx/etcdcerts/client-key.pem -x kubernetes"
time="2020-08-18T19:53:22Z" level=info msg="OCI-Monitor computed version v2.5.1-g1e7eecc3-dirty"
time="2020-08-18T19:53:22Z" level=error msg="Following dirs/files must be mounted into this container: /opt/pwx, /etc/systemd/system, /host_proc/1/ns"
time="2020-08-18T19:53:22Z" level=info msg="> run-host: /bin/sh -c systemctl show-environment"
time="2020-08-18T19:53:22Z" level=info msg="> run-host: /bin/sh -c initctl version"
time="2020-08-18T19:53:22Z" level=error msg="No suitable service controller for this platform and/or mounts configuration"
time="2020-08-18T19:53:22Z" level=error msg="Could not init service controls: Could not initialize service controller"
```

**What you expected to happen**:
Since I chose Docker type of deployment and not OCI in my values file, I expected that these mounts wouldn't be necessary:
>/opt/pwx, /etc/systemd/system, /host_proc/1/ns

**How to reproduce it (as minimally and precisely as possible)**:
My answer file is like this:
```
# Please uncomment and specify values for these options as per your requirements.

deploymentType: docker                     # accepts "oci" or "docker"
imageType: docker
imageVersion: 2.5.1                     # Version of the PX Image.

openshiftInstall: false                 # Defaults to false for installing Portworx on Openshift .
isTargetOSCoreOS: false                 # Is your target OS CoreOS? Defaults to false.
pksInstall: false                       # installation on PKS (Pivotal Container Service)
EKSInstall: false                     # installation on EKS.
AKSInstall: false                      # installation on AKS
etcdEndPoint: etcd:http://server1:2379;http://server2:2379
clusterName: ebdc-poc
usefileSystemDrive: false             # true/false Instructs PX to use an unmounted Drive even if it has a filesystem.
usedrivesAndPartitions: true          # Defaults to false. Change to true and PX will use unmounted drives and partitions.
secretType: k8s                       # Defaults to k8s, but can be kvdb/k8s/aws-kms/vault/ibm-kp. It is autopopulated to ibm-kp if the environment is IKS.
drives: /dev/sdc
dataInterface: none                   # Name of the interface <ethX>
managementInterface: none             # Name of the interface <ethX>
envVars: none                         # NOTE: This is a ";" seperated list of environment variables. For eg: MYENV1=myvalue1;MYENV2=myvalue2

stork: true                           # Use Stork https://docs.portworx.com/scheduler/kubernetes/stork.html for hyperconvergence.
storkVersion: 2.4.0

customRegistryURL:
registrySecret:

lighthouse: true
lighthouseVersion: 2.0.7
lighthouseSyncVersion: 2.0.7
lighthouseStorkConnectorVersion: 2.0.7
monitoring: false

journalDevice:

deployOnMaster: true
csi: false

internalKVDB: false                   # internal KVDB

etcd:
  credentials: none:none              # Username and password for ETCD authentication in the form user:password
  certPath: /etc/pwx/etcdcerts
  ca: /etc/pwx/etcdcerts/ca.pem
  cert: /etc/pwx/etcdcerts/client.pem
  key: /etc/pwx/etcdcerts/client-key.pem
consul:
  token: none                         # ACL token value used for Consul authentication. (example: 398073a8-5091-4d9c-871a-bbbeb030d1f6)

tolerations:                          # Add tolerations
  #  - key: "key"
  #    operator: "Equal|Exists"
  #    value: "value"
  #    effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

serviceAccount:
  hook:
    create: true
    name:

clusterToken:
  create: false                    # Create cluster token
  secretName: px-vol-encryption    # Name of kubernetes secret to be created. Requires clusterToken.create to be true.
  serviceAccountName: px-create-cluster-token # Service account name to use for post-install hook to create cluster token

replicas: 2

#requirePxEnabledTag: true               # if set to true, portworx will only install on nodes with px/enabled: true label. Not required in most scenarios.
```

**Anything else we need to know?**:

**Environment**:
- Container Orchestrator and version: Docker Community 18.09.7
- Cloud provider or hardware configuration: Local virtual machines
- OS (e.g. from /etc/os-release): RHEL 7
- Kernel (e.g. `uname -a`): 3.10.0-1062
- Install tools: Helm Chart
