### ISSUE TITLE
How DaemonSet portworx-api works?

### ISSUE THREAD

**Issue by andy812** [portworx/helm#403]
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: portworx-api
  namespace: kube-system
  labels:
    name: portworx-api
spec:
  selector:
    matchLabels:
      name: portworx-api
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        name: portworx-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: px/enabled
                    operator: {{ template "px.affinityPxEnabledOperator" . }}
                    values:
                      -  {{ template "px.affinityPxEnabledValue" . }}
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      hostNetwork: true
      hostPID: false
      containers:
        - name: portworx-api
          image: "{{ template "px.getPauseImage" . }}/pause:3.1"
          imagePullPolicy: {{ $pullPolicy }}
          readinessProbe:
            periodSeconds: 10
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 9001
      restartPolicy: Always
      serviceAccountName: px-account
```
I don't understand how it works. As i see there is the only one `pause` container what do nothing. It doesn't listen port 9001, so readinessProbe always fail. 
Could you explain how it should work?
