### ISSUE TITLE
px-lighthouse init-config container won't start, can't list resource "nodes"

### ISSUE THREAD

**Issue by nrxr** [portworx/helm#76]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
```
time="2019-02-03T16:38:13Z" level=info msg="Creating new default config for lighthouse"
2019/02/03 16:38:13 nodes is forbidden: User "system:serviceaccount:kube-system:px-lh-account" cannot list resource "nodes" in API group "" at the cluster scope Next retry in: 10s
```

**What you expected to happen**:
To work.

**How to reproduce it (as minimally and precisely as possible)**:
Just run a default installation.

**Anything else we need to know?**:
The role binding of `px-lh-account` is against `px-lh-role` which only has:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: px-lh-role
   namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update"]
```

No `resources: ["nodes"]` there so obviously it won't be able to list them. Should this be the same as `node-get-put-list-role` that's using the `px-account` Service Account?

**Environment**:
- Container Orchestrator and version: kubernetes 1.13
- Cloud provider or hardware configuration: -
- OS (e.g. from /etc/os-release): Ubuntu Bionic
- Kernel (e.g. `uname -a`): -
- Install tools: heml
- Others: -
